model_params:
  name: "VQVAE"
  in_channels: 3
  embedding_dim: 128
  num_embeddings: 512
  img_size: 32
  beta: 0.01 # Default 0.25

exp_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  devices: 1
  max_epochs: 50000
  check_val_every_n_epoch: 1000

logging_params:
  save_dir: "logs/"
  name: "VQVAE_gray"
